telegramClusterChatId: "-5238510786"
telegramMediaServerChatId: "-1003897659442"

mediaServerNodeName: "compute-vm-4-4-128-ssd-1772141617672"

redpanda:
  kafkaPort: 9092
  topics:
    - name: telegram-webhook-data-topic
      partitions: 1
    - name: tg-send-to-media-server-topic
      partitions: 1
    - name: torrent-files-topic
      partitions: 1
    - name: qbittorrent-webui-password-topic
      partitions: 1
