redpanda:
  kafkaPort: 9092
  topics:
    - name: telegram-webhook-data-topic
      partitions: 1
    - name: tg-send-to-media-server-topic
      partitions: 1
    - name: vault-unseal-topic
      partitions: 1
    - name: qbittorrent-webui-password-topic
      partitions: 1
