# TODO: Remove duplications using helmfile
clusterRootPath: /k3s-cluster

nextjs:
  enabled: true
  vps: hetzner

webdavSenaevCom:
  enabled: true
  volumePath: volumes/webdav
  vps: hetzner

webdavSenaevRu:
  enabled: true
  vps: yandex-cloud

xrayVpn:
  enabled: true
  vps: yandex-cloud

xraySocks:
  enabled: true
  vps: hetzner

qbittorrent:
  enabled: true
  volumePath: volumes/qbittorrent
  vps: yandex-cloud
  webuiPort: 9001
  torrentPort: 6881
  paths:
    complete: /downloads/complete
    incomplete: /downloads/incomplete
    watch: /downloads/watch-torrent-files
    archiveTorrents: /downloads/archive-torrent-files
    convertedForMobile: /downloads/converted-for-mobile

filebrowser:
  enabled: true
  vps: yandex-cloud
  volumePath: volumes/filebrowser/config

unmanic:
  enabled: true
  vps: yandex-cloud
  volumePath: volumes/unmanic

jellyfin:
  enabled: true
  volumePath: volumes/jellyfin
  vps: yandex-cloud
  webuiPort: 8096

testEcho:
  enabled: true
  vps: hetzner

helper:
  enabled: true
  vps: hetzner

ingress:
  entries:
    - name: senaev-com
      className: traefik-hetzner
      hosts:
        - host: senaev.com
          service: nextjs-app
          port: 3000
        - host: webdav.senaev.com
          service: webdav-senaev-com
          port: 80
        - host: test.senaev.com
          service: test-echo
          port: 80
        - host: qbittorrent.senaev.com
          service: qbittorrent
          port: 9001
        - host: filebrowser.senaev.com
          service: filebrowser
          port: 8080
        - host: jellyfin.senaev.com
          service: jellyfin
          port: 8096
        - host: senaev.ru
          service: nextjs-app
          port: 3000
        - host: webdav.senaev.ru
          service: webdav-senaev-ru
          port: 80
    - name: senaev-com-unmanic
      className: traefik-hetzner
      middleware: unmanic-basicauth
      hosts:
        - host: unmanic.senaev.com
          service: unmanic
          port: 8888

