# TODO: Remove duplications using helmfile
controlPlaneUserRootPath: /root
mediaServerUserRootPath: /home/ubuntu

nextjs:
  enabled: true
  vps: hetzner

webdav:
  enabled: true
  volumePath: k3s-cluster/volumes/webdav
  vps: hetzner

xray:
  enabled: true
  vps: yandex-cloud

qbittorrent:
  enabled: true
  volumePath: k3s-cluster/volumes/qbittorrent
  vps: yandex-cloud
  webuiPort: 9001
  torrentPort: 6881

filebrowser:
  enabled: true
  vps: yandex-cloud
  volumePath: k3s-cluster/volumes/filebrowser/config

jellyfin:
  enabled: true
  volumePath: k3s-cluster/volumes/jellyfin
  vps: yandex-cloud
  webuiPort: 8096

testEcho:
  enabled: true
  vps: hetzner

helper:
  enabled: true
  vps: hetzner

ingress:
  className: traefik
  tls:
    hosts:
      - senaev.com
      - senaev.ru
      - webdav.senaev.com
      - test.senaev.com
      - qbittorrent.senaev.com
      - filebrowser.senaev.com
      - jellyfin.senaev.com
  hosts:
    - host: senaev.com
      service: nextjs-app
      port: 3000
    - host: senaev.ru
      service: nextjs-app
      port: 3000
    - host: webdav.senaev.com
      service: webdav
      port: 80
    - host: test.senaev.com
      service: test-echo
      port: 80
    - host: qbittorrent.senaev.com
      service: qbittorrent
      # TODO: Remove this once qbittorrent.webuiPort is used in template
      port: 9001
    - host: filebrowser.senaev.com
      service: filebrowser
      port: 8080
    - host: jellyfin.senaev.com
      service: jellyfin
      port: 8096

