{{- if .Values.qbittorrent.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: {{ .Release.Namespace }}
  labels:
    app: qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      nodeSelector:
        vps: {{ .Values.qbittorrent.vps }}
      containers:
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Etc/UTC
            - name: WEBUI_PORT
              value: "{{ .Values.qbittorrent.webuiPort }}"
            - name: TORRENTING_PORT
              value: "6881"
          ports:
            - containerPort: {{ .Values.qbittorrent.webuiPort }}
              name: webui
            - containerPort: 6881
              name: torrent-tcp
            - containerPort: 6881
              name: torrent-udp
              protocol: UDP
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
      volumes:
        - name: config
          hostPath:
            path: {{ .Values.userRootPath }}/{{ .Values.qbittorrent.volumePath }}/config
            type: DirectoryOrCreate
        - name: downloads
          hostPath:
            path: {{ .Values.userRootPath }}/{{ .Values.qbittorrent.volumePath }}/downloads
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: qbittorrent
  ports:
    - name: webui
      port: {{ .Values.qbittorrent.webuiPort }}
      targetPort: {{ .Values.qbittorrent.webuiPort }}
    - name: torrent-tcp
      port: 6881
      targetPort: 6881
    - name: torrent-udp
      port: 6881
      targetPort: 6881
      protocol: UDP
{{- end }}
