apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: senaev-com-alerts
  namespace: telemetry
spec:
  groups:
    - name: overheating
      rules:
        - alert: node-overheating
          expr: |
            node_hwmon_temp_celsius{job="node-exporter",cluster=~".*"} > 100
          for: 10s
          labels:
            severity: critical
            route: senaev-com-alerts
    - name: node-disk
      rules:
        - alert: node-disk-space-low
          expr: |
            (
              node_filesystem_avail_bytes{fstype!="", job="node-exporter"} < 5 * 1024 * 1024 * 1024
            )
            and
            (
              node_filesystem_size_bytes{fstype!="", job="node-exporter"} > 10 * 1024 * 1024 * 1024
            )
          for: 10s
          labels:
            severity: warning
            route: senaev-com-alerts
    - name: node-connectivity
      rules:
        - alert: node-connectivity-failed-to-node-media
          expr: |
            kube_node_status_condition{node="{{ .Values.mediaServerNodeName }}", condition="Ready", status="true"} != 1
          for: 60s
          labels:
            severity: critical
            route: senaev-com-alerts
