apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: senaev-com-alerts
  namespace: telemetry
spec:
  groups:
    - name: node-disk
      rules:
        - alert: node-disk-space-low
          expr: |
            (
              node_filesystem_avail_bytes{mountpoint="/", fstype!="", job="node-exporter"}
              /
              node_filesystem_size_bytes{mountpoint="/", fstype!="", job="node-exporter"}
            ) < 0.11
            and
            node_filesystem_readonly{mountpoint="/", fstype!="", job="node-exporter"} == 0
          for: 10s
          labels:
            severity: warning
            route: senaev-com-alerts
