# Send telegram messages to channel via Kafka (pandaproxy):
# curl -X POST redpanda/topics/tg-send-to-media-server-topic -H "Content-Type: application/vnd.kafka.json.v2+json" -d '{"records":[{"value":"Hello, world!"}]}'
{{- if .Values.clusterHelper.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-helper
  namespace: {{ .Release.Namespace }}
  labels:
    app: cluster-helper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-helper
  template:
    metadata:
      labels:
        app: cluster-helper
      annotations:
        secret.reloader.stakater.com/reload: "senaev-com-kv-secrets"
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      nodeSelector:
        vps: {{ .Values.clusterHelper.vps }}
      initContainers:
        - name: fix-watch-folder-permissions
          image: busybox:1.37.0-uclibc
          securityContext:
            runAsUser: 0
          command:
            - sh
            - -c
            - |
              mkdir -p /watch-torrent-files
              chown -R 1000:1000 /watch-torrent-files
          volumeMounts:
            - name: watch-torrent-files
              mountPath: /watch-torrent-files
      containers:
        - name: cluster-helper
          image: ghcr.io/senaev/cluster-helper:latest
          env:
            - name: TOKEN_senaev_com_bot
              valueFrom:
                secretKeyRef:
                  name: senaev-com-kv-secrets
                  key: TOKEN_senaev_com_bot
                  optional: false
            - name: TG_MEDIA_SERVER_CHANNEL_ID
              valueFrom:
                secretKeyRef:
                  name: senaev-com-kv-secrets
                  key: TG_MEDIA_SERVER_CHANNEL_ID
                  optional: false
            - name: WATCH_TORRENT_FILES_DIR
              value: /watch-torrent-files
            - name: KAFKA_BROKERS
              value: redpanda.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.redpanda.kafkaPort }}
          ports:
            - containerPort: 80
              name: internal
            - containerPort: 3000
              name: webhook
          volumeMounts:
            - name: watch-torrent-files
              mountPath: /watch-torrent-files
      volumes:
        - name: watch-torrent-files
          hostPath:
            path: {{ .Values.clusterRootPath }}/{{ .Values.qbittorrent.volumePath }}{{ .Values.qbittorrent.paths.watch }}
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: cluster-helper
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: cluster-helper
  ports:
    - name: internal
      port: 80
      targetPort: 80
    - name: webhook
      port: 3000
      targetPort: 3000
{{- end }}