{{- if .Values.clusterHelper.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-helper
  namespace: {{ .Release.Namespace }}
  labels:
    app: cluster-helper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-helper
  template:
    metadata:
      labels:
        app: cluster-helper
        admission.datadoghq.com/enabled: "true"
        tags.datadoghq.com/service: cluster-helper
        tags.datadoghq.com/env: prod
        tags.datadoghq.com/version: latest
      annotations:
        secret.reloader.stakater.com/reload: "senaev-com-kv-secrets"
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      nodeSelector:
        vps: {{ .Values.clusterHelper.vps }}
      containers:
        - name: cluster-helper
          image: ghcr.io/senaev/cluster-helper:latest
          env:
            - name: TG_TOKEN_SENAEV_COM_BOT
              valueFrom:
                secretKeyRef:
                  name: senaev-com-kv-secrets
                  key: TG_TOKEN_SENAEV_COM_BOT
                  optional: false
            - name: TG_CLUSTER_CHAT_ID
              value: {{ .Values.telegramClusterChatId | quote }}
            - name: TG_MEDIA_SERVER_CHAT_ID
              value: {{ .Values.telegramMediaServerChatId | quote }}
          ports:
            - containerPort: 80
              name: internal
            - containerPort: 3000
              name: webhook
          livenessProbe:
            httpGet:
              path: /health/live
              port: internal
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health/ready
              port: internal
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: cluster-helper
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: cluster-helper
  ports:
    - name: internal
      port: 80
      targetPort: 80
    - name: webhook
      port: 3000
      targetPort: 3000
{{- end }}
