apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: senaev-com-kv-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: vault-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: senaev-com-kv-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: WEBDAV_COM_PASSWORD
      remoteRef:
        key: senaev-com-kv
        property: WEBDAV_COM_PASSWORD
    - secretKey: WEBDAV_RU_PASSWORD
      remoteRef:
        key: senaev-com-kv
        property: WEBDAV_RU_PASSWORD
    - secretKey: XRAY_USER_UUID
      remoteRef:
        key: senaev-com-kv
        property: XRAY_USER_UUID
    - secretKey: XRAY_REALITY_PRIVATE_KEY
      remoteRef:
        key: senaev-com-kv
        property: XRAY_REALITY_PRIVATE_KEY
    - secretKey: XRAY_REALITY_PUBLIC_KEY
      remoteRef:
        key: senaev-com-kv
        property: XRAY_REALITY_PUBLIC_KEY
    - secretKey: VPN_SUBSCRIPTION_SECRET
      remoteRef:
        key: senaev-com-kv
        property: VPN_SUBSCRIPTION_SECRET
    - secretKey: VPN_SUBSCRIPTION_CHAT
      remoteRef:
        key: senaev-com-kv
        property: VPN_SUBSCRIPTION_CHAT
    - secretKey: TG_TOKEN_SENAEV_COM_BOT
      remoteRef:
        key: senaev-com-kv
        property: TG_TOKEN_SENAEV_COM_BOT
    - secretKey: QBITTORRENT_WEBUI_PASSWORD
      remoteRef:
        key: senaev-com-kv
        property: QBITTORRENT_WEBUI_PASSWORD
    {{- range .Values.prowlarr.secretEnv }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: senaev-com-kv
        property: {{ .secretKey }}
    {{- end }}
    - secretKey: FILEBROWSER_PASSWORD_HASH
      remoteRef:
        key: senaev-com-kv
        property: FILEBROWSER_PASSWORD_HASH
    - secretKey: ALISA_WEBHOOK_SECRET
      remoteRef:
        key: senaev-com-kv
        property: ALISA_WEBHOOK_SECRET
    - secretKey: OPENROUTER_API_KEY
      remoteRef:
        key: senaev-com-kv
        property: OPENROUTER_API_KEY
    - secretKey: SUPABASE_PROJECT_URL
      remoteRef:
        key: senaev-com-kv
        property: SUPABASE_PROJECT_URL
    - secretKey: SUPABASE_PUBLISHABLE_KEY
      remoteRef:
        key: senaev-com-kv
        property: SUPABASE_PUBLISHABLE_KEY
    - secretKey: OBSIDIAN_AUTH_TOKEN
      remoteRef:
        key: senaev-com-kv
        property: OBSIDIAN_AUTH_TOKEN
    - secretKey: OBSIDIAN_VAULT_NAME
      remoteRef:
        key: senaev-com-kv
        property: OBSIDIAN_VAULT_NAME
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: senaev-com-kv
        property: OPENAI_API_KEY
    - secretKey: TG_TOKEN_SENAEV_OBSIDIAN_SYNC_BOT
      remoteRef:
        key: senaev-com-kv
        property: TG_TOKEN_SENAEV_OBSIDIAN_SYNC_BOT
    - secretKey: TG_SENAEV_USER_ID
      remoteRef:
        key: senaev-com-kv
        property: TG_SENAEV_USER_ID
    - secretKey: GROQ_API_KEY
      remoteRef:
        key: senaev-com-kv
        property: GROQ_API_KEY
