apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: senaev-com-kv-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: vault-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: senaev-com-kv-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: WEBDAV_COM_PASSWORD
      remoteRef:
        key: senaev-com-kv
        property: WEBDAV_COM_PASSWORD
    - secretKey: WEBDAV_RU_PASSWORD
      remoteRef:
        key: senaev-com-kv
        property: WEBDAV_RU_PASSWORD
    - secretKey: XRAY_USER_UUID
      remoteRef:
        key: senaev-com-kv
        property: XRAY_USER_UUID
    - secretKey: XRAY_REALITY_PRIVATE_KEY
      remoteRef:
        key: senaev-com-kv
        property: XRAY_REALITY_PRIVATE_KEY
    - secretKey: XRAY_REALITY_PUBLIC_KEY
      remoteRef:
        key: senaev-com-kv
        property: XRAY_REALITY_PUBLIC_KEY
    - secretKey: VPN_SUBSCRIPTION_SECRET
      remoteRef:
        key: senaev-com-kv
        property: VPN_SUBSCRIPTION_SECRET
    - secretKey: VPN_SUBSCRIPTION_CHAT
      remoteRef:
        key: senaev-com-kv
        property: VPN_SUBSCRIPTION_CHAT
    - secretKey: TG_TOKEN_SENAEV_COM_BOT
      remoteRef:
        key: senaev-com-kv
        property: TG_TOKEN_SENAEV_COM_BOT
    - secretKey: FILEBROWSER_PASSWORD_HASH
      remoteRef:
        key: senaev-com-kv
        property: FILEBROWSER_PASSWORD_HASH
    - secretKey: ALISA_WEBHOOK_SECRET
      remoteRef:
        key: senaev-com-kv
        property: ALISA_WEBHOOK_SECRET
    - secretKey: OPENROUTER_API_KEY
      remoteRef:
        key: senaev-com-kv
        property: OPENROUTER_API_KEY
    - secretKey: GOOGLE_KEEP_AUTH_TOKEN
      remoteRef:
        key: senaev-com-kv
        property: GOOGLE_KEEP_AUTH_TOKEN
