{{- if .Values.mediaServerHelper.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-server-helper
  namespace: {{ .Release.Namespace }}
  labels:
    app: media-server-helper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media-server-helper
  template:
    metadata:
      labels:
        app: media-server-helper
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      nodeSelector:
        vps: {{ .Values.mediaServerHelper.vps }}
      initContainers:
        - name: fix-watch-folder-permissions
          image: busybox:1.37.0-uclibc
          securityContext:
            runAsUser: 0
          command:
            - sh
            - -c
            - |
              mkdir -p /watch-torrent-files
              chown -R 1000:1000 /watch-torrent-files
          volumeMounts:
            - name: watch-torrent-files
              mountPath: /watch-torrent-files
      containers:
        - name: media-server-helper
          image: ghcr.io/senaev/media-server-helper:latest
          env:
            - name: KAFKA_BROKERS
              value: redpanda.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.redpanda.kafkaPort }}
            - name: TORRENT_FILES_DIR
              value: /watch-torrent-files
          volumeMounts:
            - name: watch-torrent-files
              mountPath: /watch-torrent-files
      volumes:
        - name: watch-torrent-files
          hostPath:
            path: {{ .Values.clusterRootPath }}/{{ .Values.qbittorrent.volumePath }}{{ .Values.qbittorrent.paths.watch }}
            type: DirectoryOrCreate
{{- end }}
