# Send telegram messages to channel:
# curl -X POST http://media-server-helper.senaev-com.svc.cluster.local/tg -H "Content-Type: text/plain" -d "Hello, world!"
# inside of namespace
# curl -X POST media-server-helper/tg -H "Content-Type: text/plain" -d "Hello, world!"
{{- if .Values.mediaServerHelper.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-server-helper
  namespace: {{ .Release.Namespace }}
  labels:
    app: media-server-helper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media-server-helper
  template:
    metadata:
      labels:
        app: media-server-helper
      annotations:
        secret.reloader.stakater.com/reload: "senaev-com-kv-secrets"
    spec:
      nodeSelector:
        vps: {{ .Values.mediaServerHelper.vps }}
      containers:
        - name: media-server-helper
          image: ghcr.io/senaev/media-server-helper.senaev.com:latest
          env:
            - name: TOKEN_senaev_com_bot
              valueFrom:
                secretKeyRef:
                  name: senaev-com-kv-secrets
                  key: TOKEN_senaev_com_bot
                  optional: false
            - name: TG_CHANNEL_ID
              valueFrom:
                secretKeyRef:
                  name: senaev-com-kv-secrets
                  key: TG_CHANNEL_ID
                  optional: false
          ports:
            - containerPort: 80
              name: internal
            - containerPort: 3000
              name: webhook
---
apiVersion: v1
kind: Service
metadata:
  name: media-server-helper
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: media-server-helper
  ports:
    - name: internal
      port: 80
      targetPort: 80
    - name: webhook
      port: 3000
      targetPort: 3000
{{- end }}