{{- if .Values.vpnSubscription.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpn-subscription
  namespace: {{ .Release.Namespace }}
  labels:
    app: vpn-subscription
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpn-subscription
  template:
    metadata:
      labels:
        app: vpn-subscription
        admission.datadoghq.com/enabled: "true"
        tags.datadoghq.com/service: vpn-subscription
        tags.datadoghq.com/env: prod
        tags.datadoghq.com/version: latest
      annotations:
        secret.reloader.stakater.com/reload: "senaev-com-kv-secrets"
    spec:
      nodeSelector:
        vps: {{ .Values.vpnSubscription.vps }}
      containers:
        - name: vpn-subscription
          image: ghcr.io/senaev/vpn-subscription:latest
          ports:
            - containerPort: 3000
          env:
            - name: SUBSCRIPTION_ENTRIES
              value: {{ toJson .Values.vpnSubscription.entries | quote }}
            - name: VPN_SUBSCRIPTION_CHAT_ID
              value: {{ .Values.telegramVpnSubscriptionChatId | quote }}
            - name: VPN_SUBSCRIPTION_SECRET
              valueFrom:
                secretKeyRef:
                  name: senaev-com-kv-secrets
                  key: VPN_SUBSCRIPTION_SECRET
                  optional: false
            - name: VPN_SUBSCRIPTION_CHAT
              valueFrom:
                secretKeyRef:
                  name: senaev-com-kv-secrets
                  key: VPN_SUBSCRIPTION_CHAT
                  optional: false
            - name: XRAY_USER_UUID
              valueFrom:
                secretKeyRef:
                  name: senaev-com-kv-secrets
                  key: XRAY_USER_UUID
                  optional: false
            - name: XRAY_REALITY_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: senaev-com-kv-secrets
                  key: XRAY_REALITY_PUBLIC_KEY
                  optional: false
---
apiVersion: v1
kind: Service
metadata:
  name: vpn-subscription
  namespace: {{ .Release.Namespace }}
  labels:
    app: vpn-subscription
spec:
  type: ClusterIP
  selector:
    app: vpn-subscription
  ports:
    - port: 3000
      targetPort: 3000
{{- end }}
