{{- if .Values.webdavSenaevRu.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: webdav-senaev-ru-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: webdav-senaev-ru
data:
  config.yml: |
    address: 0.0.0.0
    port: 80
    prefix: /
    directory: /data
    permissions: CRUD

    users:
      - username: webdav_admin
        password: "{env}WEBDAV_RU_PASSWORD"
        permissions: CRUD
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdav-senaev-ru
  namespace: {{ .Release.Namespace }}
  labels:
    app: webdav-senaev-ru
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webdav-senaev-ru
  template:
    metadata:
      labels:
        app: webdav-senaev-ru
      annotations:
        secret.reloader.stakater.com/reload: "senaev-com-kv-secrets"
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      nodeSelector:
        vps: {{ .Values.webdavSenaevRu.vps }}
      containers:
        - name: webdav
          image: hacdias/webdav:latest
          args:
            - -c
            - /config/config.yml
          env:
            - name: WEBDAV_RU_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: senaev-com-kv-secrets
                  key: WEBDAV_RU_PASSWORD
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
            - name: media
              mountPath: /data
      volumes:
        - name: config
          configMap:
            name: webdav-senaev-ru-config
        - name: media
          hostPath:
            path: {{ .Values.clusterRootPath }}/{{ .Values.qbittorrent.volumePath }}/downloads
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: webdav-senaev-ru
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: webdav-senaev-ru
  ports:
    - port: 80
      targetPort: 80
{{- end }}
