# TODO: Remove duplications using helmfile
userRootPath: /root

nextjs:
  enabled: true
  image: ghcr.io/senaev/senaev.com:latest
  vps: hetzner

webdav:
  enabled: true
  image: bytemark/webdav
  volumePath: k3s-cluster/volumes/webdav
  vps: hetzner

xray:
  enabled: true
  image: teddysun/xray:latest
  vps: ionos

testEcho:
  enabled: true
  image: hashicorp/http-echo:0.2.3
  vps: hetzner

ingress:
  className: traefik
  tls:
    hosts:
      - senaev.com
      - senaev.ru
      - webdav.senaev.com
      - test.senaev.com
  hosts:
    - host: senaev.com
      service: nextjs-app
      port: 3000
    - host: senaev.ru
      service: nextjs-app
      port: 3000
    - host: webdav.senaev.com
      service: webdav
      port: 80
    - host: test.senaev.com
      service: test-echo
      port: 80

