enabled: true

deployments:
  - vps: hetzner
  - vps: firstvds
  - vps: vultr
  - vps: netcup

resources:
  requests:
    cpu: 25m
    memory: 64Mi

acmeStoragePath: /k3s-cluster/volumes/traefik/acme

image: traefik:v3.2

acme:
  email: andrei.senaev@gmail.com
