create table if not exists public.lists (
    id bigint generated by default as identity primary key,
    title text not null,
    created timestamptz not null default timezone('utc', now()),
    updated timestamptz not null default timezone('utc', now())
);

create or replace function public.handle_lists_update()
returns trigger
language plpgsql
as $$
begin
    new.updated = timezone('utc', now());
    return new;
end;
$$;

drop trigger if exists handle_lists_update on public.lists;
create trigger handle_lists_update
    before update on public.lists
    for each row
    execute procedure public.handle_lists_update();

create table if not exists public.lists_items (
    id bigint generated by default as identity primary key,
    list_id bigint not null,
    child boolean not null,
    title text not null,
    position integer not null,
    created timestamptz not null default timezone('utc', now()),
    updated timestamptz not null default timezone('utc', now()),
    check_time timestamp default null,
    update_index bigint not null
);

create or replace function public.handle_lists_items_update()
returns trigger
language plpgsql
as $$
begin
    if new.update_index <= old.update_index then
        raise exception
            '%',
            json_build_object(
                'id',
                'update_index_conflict',
                'text',
                format(
                    'update_index must be greater than current value (current %s, got %s)',
                    old.update_index,
                    new.update_index
                ),
                'current_update_index',
                old.update_index,
                'requested_update_index',
                new.update_index
            )::text;
    end if;

    new.updated = timezone('utc', now());
    return new;
end;
$$;

drop trigger if exists handle_lists_items_update on public.lists_items;
create trigger handle_lists_items_update
    before update on public.lists_items
    for each row
    execute procedure public.handle_lists_items_update();
