create extension if not exists moddatetime schema extensions;

create table if not exists public.grocery_items (
    id bigint generated by default as identity primary key,
    title text not null,
    position integer not null,
    created timestamptz not null default timezone('utc', now()),
    updated timestamptz not null default timezone('utc', now()),
    checked boolean not null default false
);

drop trigger if exists handle_grocery_items_updated on public.grocery_items;
create trigger handle_grocery_items_updated
    before update on public.grocery_items
    for each row
    execute procedure extensions.moddatetime(updated);
