victoria-metrics-k8s-stack:
  # Victoria Metrics Operator is installed separately
  # https://docs.victoriametrics.com/helm/victoria-metrics-k8s-stack/#install-operator-separately
  victoria-metrics-operator:
    enabled: false
    crds:
      cleanup:
        enabled: false

  grafana:
    enabled: true
    nodeSelector:
      vps: hetzner
    annotations:
      secret.reloader.stakater.com/reload: "senaev-com-kv-secrets"
    admin:
      existingSecret: senaev-com-kv-secrets
      userKey: GRAFANA_ADMIN_USER
      passwordKey: GRAFANA_ADMIN_PASSWORD
    ingress:
      enabled: true
      ingressClassName: traefik-hetzner
      path: /
      pathType: Prefix
      hosts:
        - grafana.senaev.com
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
      tls:
        - hosts:
            - grafana.senaev.com

  vmsingle:
    ingress:
      enabled: true
      ingressClassName: traefik-hetzner
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
        traefik.ingress.kubernetes.io/router.middlewares: "{{ .Release.Namespace }}-victoriametrics-basicauth@kubernetescrd"
      hosts:
        - victoriametrics.senaev.com
      tls:
        - hosts:
            - victoriametrics.senaev.com
    spec:
      retentionPeriod: "3"
      nodeSelector:
        vps: hetzner

  vmagent:
    spec:
      scrapeInterval: 30s
      nodeSelector:
        vps: hetzner

  alertmanager:
    ingress:
      enabled: true
      ingressClassName: traefik-hetzner
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
        traefik.ingress.kubernetes.io/router.middlewares: "{{ .Release.Namespace }}-alertmanager-basicauth@kubernetescrd"
      hosts:
        - alertmanager.senaev.com
      tls:
        - hosts:
            - alertmanager.senaev.com
    spec:
      externalURL: https://alertmanager.senaev.com
      nodeSelector:
        vps: hetzner
    useManagedConfig: true
    config:
      route:
        receiver: blackhole
        routes:
          - matchers:
              - route="senaev-com-alerts"
            receiver: telegram-alerts-receiver
            group_wait: 0s
            group_interval: 10s
            repeat_interval: 1h
      receivers:
        - name: blackhole
        - name: telegram-alerts-receiver
          webhook_configs:
            - url: http://cluster-helper.senaev-com.svc.cluster.local/alertmanager/webhook
              send_resolved: true

  vmalert:
    ingress:
      enabled: true
      ingressClassName: traefik-hetzner
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
        traefik.ingress.kubernetes.io/router.middlewares: "{{ .Release.Namespace }}-vmalert-basicauth@kubernetescrd"
      hosts:
        - vmalert.senaev.com
      tls:
        - hosts:
            - vmalert.senaev.com
    spec:
      evaluationInterval: 30s
      nodeSelector:
        vps: hetzner

  kube-state-metrics:
    nodeSelector:
      vps: hetzner

smokepingProber:
  enabled: true
  namespace: telemetry
  port: 9374
  scrapeInterval: 120s
  targets:
    - hetzner
    - firstvds
    - senaev-media
    - senaev.com
    - senaev.ru
  extraTargets: []
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi

iperf3Monitor:
  enabled: true
  sourceVpsList:
    - hetzner
    - firstvds
    - senaev-media
    - vultr
  tests:
    - source: hetzner
      target: firstvds
    - source: firstvds
      target: hetzner
    - source: senaev-media
      target: hetzner
    - source: vultr
      target: firstvds
    - source: firstvds
      target: vultr
    - source: hetzner
      target: vultr
    - source: vultr
      target: hetzner
    - source: senaev-media
      target: firstvds
  scheduler:
    enabled: true
    vps: hetzner
    port: 9579
    pauseBetweenTests: 300
    scrapeInterval: 30s
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 128Mi
  agent:
    port: 9580
    period: 10
    timeout: 30
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 128Mi
  server:
    port: 5201
