name: vpn-subscription

on:
  push:
    branches: [main, master]
    paths:
      - "vpn-subscription/**"
  workflow_dispatch:

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-service.yml
    with:
      workflow_title: vpn-subscription
      context: ./vpn-subscription
      registry_image: ghcr.io/senaev/vpn-subscription
      deployment_name: vpn-subscription
    secrets: inherit
