name: cluster-helper

on:
  push:
    branches: [main, master]
    paths:
      - "cluster-helper/**"
  workflow_dispatch:

jobs:
  build-and-push:
    uses: ./.github/workflows/build-service.yml
    with:
      workflow_title: cluster-helper
      context: ./cluster-helper
      registry_image: ghcr.io/senaev/cluster-helper
    secrets: inherit
