name: media-server-helper

on:
  push:
    branches: [main, master]
    paths:
      - "media-server-helper/**"
  workflow_dispatch:

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-service.yml
    with:
      workflow_title: media-server-helper
      context: ./media-server-helper
      registry_image: ghcr.io/senaev/media-server-helper
      deployment_name: media-server-helper
    secrets: inherit
