name: torrent-files-writer

on:
  push:
    branches: [main, master]
    paths:
      - "torrent-files-writer/**"
  workflow_dispatch:

jobs:
  build-and-push:
    uses: ./.github/workflows/build-service.yml
    with:
      workflow_title: torrent-files-writer
      context: ./torrent-files-writer
      registry_image: ghcr.io/senaev/torrent-files-writer
    secrets: inherit
