name: Build VPN Subscription

on:
  push:
    branches: [main, master]
    paths:
      - "vpn-subscription/**"
  workflow_dispatch:

jobs:
  build-and-push:
    uses: ./.github/workflows/build-service.yml
    with:
      workflow_title: Build VPN Subscription
      context: ./vpn-subscription
      registry_image: ghcr.io/senaev/vpn-subscription
    secrets: inherit
